version: '2'
services:
  # The Database
  database:
    image: mariadb
    volumes:
      - ./docker/db:/var/lib/mysql:rw
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "3306:3306"

  # The Application
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - DB_HOST=database

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8000:80